import type { Invoice } from "@/types/invoice";

const today = new Date();
const date = (offset: number) => {
  const value = new Date(today);
  value.setDate(value.getDate() + offset);
  return value.toISOString().slice(0, 10);
};

export const demoInvoices: Invoice[] = [
  {
    id: "demo-1",
    organization_id: "demo-org",
    invoice_number: "FV-2026-084",
    counterparty_name: "Stavby Novák s.r.o.",
    counterparty_ico: "08342156",
    counterparty_dic: "CZ08342156",
    counterparty_email: "fakturace@stavbynovak.cz",
    variable_symbol: "2026084",
    amount_without_vat: 152479.34,
    vat_rate: 21,
    amount: 184500,
    paid_amount: 50000,
    currency: "CZK",
    issue_date: date(-23),
    due_date: date(-9),
    status: "overdue",
    source: "manual",
    file_url: null,
    notes: "Dodávka konstrukčního řeziva",
    paid_at: null,
    reminders_sent: 2,
    last_reminder_at: date(-2),
    next_reminder_at: date(5),
    reminders_paused: false,
    reminders_paused_at: null,
    reminders_paused_by: null,
    updated_by: null,
    created_at: date(-23),
    updated_at: date(-2),
  },
  {
    id: "demo-2",
    organization_id: "demo-org",
    invoice_number: "FV-2026-091",
    counterparty_name: "Dřevostavby Morava a.s.",
    counterparty_ico: "27659312",
    counterparty_dic: "CZ27659312",
    counterparty_email: "uctarna@drevo-morava.cz",
    variable_symbol: "2026091",
    amount_without_vat: 79958.68,
    vat_rate: 21,
    amount: 96750,
    paid_amount: 0,
    currency: "CZK",
    issue_date: date(-8),
    due_date: date(6),
    status: "pending",
    source: "ocr",
    file_url: null,
    notes: null,
    paid_at: null,
    reminders_sent: 0,
    last_reminder_at: null,
    next_reminder_at: date(3),
    reminders_paused: false,
    reminders_paused_at: null,
    reminders_paused_by: null,
    updated_by: null,
    created_at: date(-8),
    updated_at: date(-8),
  },
  {
    id: "demo-3",
    organization_id: "demo-org",
    invoice_number: "FV-2026-073",
    counterparty_name: "Krovservis CZ s.r.o.",
    counterparty_ico: "04791288",
    counterparty_dic: "CZ04791288",
    counterparty_email: "info@krovservis.cz",
    variable_symbol: "2026073",
    amount_without_vat: 204380.17,
    vat_rate: 21,
    amount: 247300,
    paid_amount: 247300,
    currency: "CZK",
    issue_date: date(-38),
    due_date: date(-24),
    status: "paid",
    source: "manual",
    file_url: null,
    notes: null,
    paid_at: date(-5),
    reminders_sent: 1,
    last_reminder_at: date(-17),
    next_reminder_at: null,
    reminders_paused: false,
    reminders_paused_at: null,
    reminders_paused_by: null,
    updated_by: null,
    created_at: date(-38),
    updated_at: date(-5),
  },
  {
    id: "demo-4",
    organization_id: "demo-org",
    invoice_number: "FV-2026-096",
    counterparty_name: "Pila Vysočina spol. s r.o.",
    counterparty_ico: "25510471",
    counterparty_dic: "CZ25510471",
    counterparty_email: "ekonom@pilavysocina.cz",
    variable_symbol: "2026096",
    amount_without_vat: 48198.35,
    vat_rate: 21,
    amount: 58320,
    paid_amount: 0,
    currency: "CZK",
    issue_date: date(-3),
    due_date: date(11),
    status: "pending",
    source: "manual",
    file_url: null,
    notes: null,
    paid_at: null,
    reminders_sent: 0,
    last_reminder_at: null,
    next_reminder_at: date(8),
    reminders_paused: false,
    reminders_paused_at: null,
    reminders_paused_by: null,
    updated_by: null,
    created_at: date(-3),
    updated_at: date(-3),
  },
];
